CREATE DATABASE DB_FILME
GO

USE DB_FILME
GO


CREATE TABLE TB_GENERO (
	id_genero INTEGER IDENTITY NOT NULL PRIMARY KEY,
	nome_genero VARCHAR(50) NOT NULL
)
GO

CREATE TABLE TB_LOCAL (
	id_local INTEGER IDENTITY NOT NULL PRIMARY KEY,
	pais_local VARCHAR(15) NOT NULL,
	estado_local VARCHAR(15) NOT NULL,
	cidade_local VARCHAR(15) NOT NULL,
	endereco_local VARCHAR(100) NOT NULL,
	complemento_local VARCHAR(15) NOT NULL
)
GO

CREATE TABLE TB_ORIGEM (
	id_origem INTEGER IDENTITY NOT NULL PRIMARY KEY,
	pais_origem VARCHAR(15) NOT NULL
)
GO

CREATE TABLE TB_DIRETOR (
	id_diretor INTEGER IDENTITY NOT NULL PRIMARY KEY,
	nome_diretor VARCHAR(50) NOT NULL
)
GO

CREATE TABLE TB_ATOR (
	id_ator INTEGER IDENTITY NOT NULL PRIMARY KEY,
	nome_ator VARCHAR(50) NOT NULL,
	idade_ator SMALLINT NOT NULL
)
GO


CREATE TABLE TB_CINEMA (
	id_cinema INTEGER IDENTITY NOT NULL PRIMARY KEY,
	nome_cinema VARCHAR(50) NOT NULL,

	fk_local INTEGER NOT NULL REFERENCES TB_LOCAL(id_local),
)
GO

CREATE TABLE TB_SALA (
	id_sala INTEGER IDENTITY NOT NULL PRIMARY KEY,
	numero_sala INTEGER NOT NULL,
	quantidade_lugares_sala INTEGER NOT NULL,

	fk_cinema INTEGER NOT NULL REFERENCES TB_CINEMA(id_cinema)
)
GO

CREATE TABLE TB_ESTUDIO (
	id_estudio INTEGER IDENTITY NOT NULL PRIMARY KEY,
	nome_estudio VARCHAR(50) NOT NULL,

	fk_origem INTEGER NOT NULL REFERENCES TB_ORIGEM(id_origem)
)
GO

CREATE TABLE TB_FILME (
	id_filme INTEGER IDENTITY NOT NULL PRIMARY KEY,
	nome_filme VARCHAR(50) NOT NULL,
	duracao_filme INTEGER NOT NULL,
	classificacao_filme SMALLINT NOT NULL,
	sinopse_filme VARCHAR(500) NOT NULL,

	fk_estudio INTEGER NOT NULL REFERENCES TB_ESTUDIO(id_estudio),
	fk_genero INTEGER NOT NULL REFERENCES TB_GENERO(id_genero),
	fk_diretor INTEGER NOT NULL REFERENCES TB_DIRETOR(id_diretor)
)
GO

CREATE TABLE TB_SESSAO (
	id_sessao INTEGER IDENTITY NOT NULL PRIMARY KEY,
	data_horario_sessao DATETIME NOT NULL,

	fk_filme INTEGER NOT NULL REFERENCES TB_FILME(id_filme),
	fk_sala INTEGER NOT NULL REFERENCES TB_SALA(id_sala)
)
GO

CREATE TABLE TB_PAPEL (
	id_papel INTEGER IDENTITY NOT NULL PRIMARY KEY,
	nome_personagem_papel VARCHAR(50) NOT NULL,
	cache_papel DECIMAL(10, 2) NOT NULL,

	fk_ator INTEGER NOT NULL REFERENCES TB_ATOR(id_ator),
	fk_filme INTEGER NOT NULL REFERENCES TB_FILME(id_filme)
)
GO

CREATE TABLE TB_INGRESSO (
	id_ingresso INTEGER IDENTITY NOT NULL PRIMARY KEY,
	valor_ingresso DECIMAL(5, 2) NOT NULL,
	lugar_ingresso CHAR(3) NOT NULL,

	fk_sala INTEGER NOT NULL REFERENCES TB_SALA(id_sala),
	fk_filme INTEGER NOT NULL REFERENCES TB_FILME(id_filme),
	fk_sessao INTEGER NOT NULL REFERENCES TB_SESSAO(id_sessao)
)
GO
