INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('20th Century Fox Film Corporation', 1)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('20th Century Fox', 2)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('Fox 2000 pictores', 3)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('Fox Searchlight Pictures', 4)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('Paramount Pictures', 5)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('MTV Films', 6)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('Nickelodeon Movies', 7)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('Famous Studios', 8)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('Paramount Classics/ Paramount Vantage', 9)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('DreamWorks', 10)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('Republic Pictures', 11)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('Sony Pictures Entertainment', 12)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('Columbia Pictures', 13)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('TriStar Pictures', 14)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('Screen Gems', 15)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('Triumph Films', 16)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('Sony Pictures Classics', 17)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('Destination Films', 18)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('NBC Universal', 19)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('Universal Studios', 20)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('Focus Features', 21)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('Warner Bros. Entertainment', 22)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('Warner Bros. Pictures', 23)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('Warner Independent Pictures', 24)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('Castle Rock Entertainment', 25)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('New Line Cinema', 26)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('HBO', 27)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('HBO Films', 28)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('Picturehouse', 29)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('Buena Vista Motion Pictures Group', 30)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('Disney Channel Original Movies', 31)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('Walt Disney Pictures', 32)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('Hollywood Pictures', 33)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('Touchstone Pictures', 34)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('Pixar Animation Studios', 35)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('Miramax Films', 36)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('Marvel Studios', 37)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('Lucasfilm', 38)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('ABC Studios.', 39)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('Outras produtoras', 40)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('Metro-Goldwyn-Mayer', 41)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('United Artists', 42)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('Orion Pictures', 43)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('Aardman Animations', 44)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('Alliance Atlantis', 45)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('Amblin Entertainment', 46)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('American Zoetrope', 47)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('American Mutoscope and Biograph Company', 48)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('Baltimore Pictures', 49)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('Bristol Bay Productions', 50)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('Canal +', 51)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('Capitol Films', 52)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('Caravan Pictures', 53)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('Carrington Productions International', 54)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('Casey Silver Productions', 55)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('CBS', 56)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('Centropolis Entertainment', 57)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('Channel Four Films', 58)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('Content Film', 59)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('Davis Entertainment', 60)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('Davis Films / Impact Canada', 61)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('Distant Horizon', 62)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('Dualstar Productions', 63)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('EMI Films', 64)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('FilmAuro', 65)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('Fireworks Pictures', 66)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('The Geffen Film Company', 67)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('Golden Harvest', 68)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('Gold Circle Films', 69)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('Greenestreet Films', 70)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('Gullane Pictures', 71)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('IFC Entertainment', 72)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('Imagine Entertainment', 73)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('Initial Entertainment Group', 74)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('Interscope Pictures', 75)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('Jim Henson Pictures', 76)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('The Kennedy/Marshall Company', 77)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('Kopelson Entertainment', 78)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('Lakeshore Entertainment', 79)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('Lyrick Studios', 80)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('Lions Gate Films', 81)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('Artisan Entertainment', 82)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('Mandalay Pictures', 83)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('Mandeville Films', 84)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('Mark IV Pictures Incorporated', 85)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('Media 8 Entertainment', 86)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('The Montecito Picture Company', 87)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('Morgan Creek Productions', 88)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('Nelson Entertainment', 89)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('New Regency', 90)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('Northern Lights Entertainment', 91)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('PolyGram Filmed Entertainment', 92)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('Producers Releasing Corporation', 93)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('Rankin-Bass', 94)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('Revere Pictures', 95)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('Revolution Studios', 96)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('RKO Pictures', 97)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('Rogue Pictures', 98)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('Salter Street Films', 99)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('The Samuel Goldwyn Company', 100)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('Seven Arts', 101)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('Spelling Films', 102)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('Spyglass Entertainment', 103)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('Strand Releasing', 104)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('StudioCanal', 105)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('Tapestry Films', 106)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('Tartan Films', 107)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('Trimark Pictures', 108)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('Troma Entertainment', 109)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('Valhalla Motion Pictures', 110)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('Vanguard Films', 111)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('Village Roadshow Pictures', 112)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('Walden Media -lohana nicoly', 113)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('The Weinstein Company', 114)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('Dimension Films', 115)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('Zeitgeist Films', 116)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('Sediadas internacionalmente', 117)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('Gaumont', 118)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('Pathe', 119)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('EuropaCorp.', 120)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('Bavaria Film', 121)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('UFA', 122)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('UGC', 123)
INSERT INTO TB_ESTUDIO (nome_estudio, fk_origem) VALUES ('PorchLight Entertainment', 124)