INSERT INTO TB_CINEMA (nome_cinema, fk_local) VALUES ('Cine Art-Palácio', 1)
INSERT INTO TB_CINEMA (nome_cinema, fk_local) VALUES ('Cine Arte Posto 4', 1)
INSERT INTO TB_CINEMA (nome_cinema, fk_local) VALUES ('Cine Santana', 1)
INSERT INTO TB_CINEMA (nome_cinema, fk_local) VALUES ('Teatro Colombo', 1)
INSERT INTO TB_CINEMA (nome_cinema, fk_local) VALUES ('Cine Ipiranga', 1)
INSERT INTO TB_CINEMA (nome_cinema, fk_local) VALUES ('Cine Metro', 1)
INSERT INTO TB_CINEMA (nome_cinema, fk_local) VALUES ('Cine Marabá', 1)
INSERT INTO TB_CINEMA (nome_cinema, fk_local) VALUES ('Cine Marrocos', 1)
INSERT INTO TB_CINEMA (nome_cinema, fk_local) VALUES ('Cine Olido', 1)
INSERT INTO TB_CINEMA (nome_cinema, fk_local) VALUES ('Cine Paissandu', 1)
INSERT INTO TB_CINEMA (nome_cinema, fk_local) VALUES ('Cine República', 1)
INSERT INTO TB_CINEMA (nome_cinema, fk_local) VALUES ('Cine 9 de Abril', 2)
INSERT INTO TB_CINEMA (nome_cinema, fk_local) VALUES ('Cine Centímetro', 2)
INSERT INTO TB_CINEMA (nome_cinema, fk_local) VALUES ('Cine Estação São Pedro', 2)
INSERT INTO TB_CINEMA (nome_cinema, fk_local) VALUES ('Cine Vitória', 2)
INSERT INTO TB_CINEMA (nome_cinema, fk_local) VALUES ('Cinema Icaraí', 2)
INSERT INTO TB_CINEMA (nome_cinema, fk_local) VALUES ('Livio Bruni', 2)
INSERT INTO TB_CINEMA (nome_cinema, fk_local) VALUES ('Cine Excelsior', 3)
INSERT INTO TB_CINEMA (nome_cinema, fk_local) VALUES ('Cine Teatro Fátima', 4)
INSERT INTO TB_CINEMA (nome_cinema, fk_local) VALUES ('UCI Aeroclube', 4)
INSERT INTO TB_CINEMA (nome_cinema, fk_local) VALUES ('Cine-Teatro São Luiz', 5)

SELECT * FROM TB_CINEMA