INSERT INTO TB_GENERO (nome_genero) VALUES ('Ação')
INSERT INTO TB_GENERO (nome_genero) VALUES ('Animação')
INSERT INTO TB_GENERO (nome_genero) VALUES ('Aventura')
INSERT INTO TB_GENERO (nome_genero) VALUES ('Chanchada')
INSERT INTO TB_GENERO (nome_genero) VALUES ('Cinema catástrofe')
INSERT INTO TB_GENERO (nome_genero) VALUES ('Comédia')
INSERT INTO TB_GENERO (nome_genero) VALUES ('Comédia romântica')
INSERT INTO TB_GENERO (nome_genero) VALUES ('Comédia dramática')
INSERT INTO TB_GENERO (nome_genero) VALUES ('Comédia de ação')
INSERT INTO TB_GENERO (nome_genero) VALUES ('Cult')
INSERT INTO TB_GENERO (nome_genero) VALUES ('Dança')
INSERT INTO TB_GENERO (nome_genero) VALUES ('Documentários')
INSERT INTO TB_GENERO (nome_genero) VALUES ('Drama')
INSERT INTO TB_GENERO (nome_genero) VALUES ('Espionagem')
INSERT INTO TB_GENERO (nome_genero) VALUES ('Erótico')
INSERT INTO TB_GENERO (nome_genero) VALUES ('Fantasia')
INSERT INTO TB_GENERO (nome_genero) VALUES ('Faroeste')
INSERT INTO TB_GENERO (nome_genero) VALUES ('Ficção científica')
INSERT INTO TB_GENERO (nome_genero) VALUES ('Franchise/Séries')
INSERT INTO TB_GENERO (nome_genero) VALUES ('Guerra')
INSERT INTO TB_GENERO (nome_genero) VALUES ('Machinima')
INSERT INTO TB_GENERO (nome_genero) VALUES ('Masala')
INSERT INTO TB_GENERO (nome_genero) VALUES ('Musical')
INSERT INTO TB_GENERO (nome_genero) VALUES ('Filme noir')
INSERT INTO TB_GENERO (nome_genero) VALUES ('Policial')
INSERT INTO TB_GENERO (nome_genero) VALUES ('Pornochanchada')
INSERT INTO TB_GENERO (nome_genero) VALUES ('Pornográfico')
INSERT INTO TB_GENERO (nome_genero) VALUES ('Romance')
INSERT INTO TB_GENERO (nome_genero) VALUES ('Seriado')
INSERT INTO TB_GENERO (nome_genero) VALUES ('Suspense')
INSERT INTO TB_GENERO (nome_genero) VALUES ('Terror')
INSERT INTO TB_GENERO (nome_genero) VALUES ('Trash')