INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Afeganistão')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('África do Sul')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Albânia')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Alemanha')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Andorra')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Angola')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Antiga e Barbuda')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Arábia Saudita')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Argélia')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Argentina')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Arménia')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Austrália')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Áustria')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Azerbaijão')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Bahamas')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Bangladexe')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Barbados')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Barém')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Bélgica')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Belize')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Benim')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Bielorrússia')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Bolívia')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Bósnia e Herzegovina')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Botsuana')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Brasil')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Brunei')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Bulgária')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Burquina Faso')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Burúndi')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Butão')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Cabo Verde')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Camarões')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Camboja')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Canadá')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Catar')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Cazaquistão')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Chade')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Chile')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('China')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Chipre')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Colômbia')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Comores')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Congo-Brazzaville')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Coreia do Norte')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Coreia do Sul')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Cosovo')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Costa do Marfim')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Costa Rica')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Croácia')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Cuaite')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Cuba')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Dinamarca')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Dominica')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Egito')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Emirados Árabes Unidos')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Equador')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Eritreia')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Eslováquia')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Eslovénia')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Espanha')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Estado da Palestina')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Estados Unidos')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Estónia')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Etiópia')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Fiji')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Filipinas')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Finlândia')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('França')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Gabão')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Gâmbia')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Gana')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Geórgia')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Granada')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Grécia')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Guatemala')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Guiana')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Guiné')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Guiné Equatorial')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Guiné-Bissau')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Haiti')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Honduras')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Hungria')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Iémen')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Ilhas Marechal')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Índia')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Indonésia')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Irão')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Iraque')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Irlanda')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Islândia')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Israel')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Itália')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Jamaica')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Japão')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Jibuti')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Jordânia')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Laus')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Lesoto')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Letónia')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Líbano')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Libéria')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Líbia')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Listenstaine')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Lituânia')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Luxemburgo')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Macedónia')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Madagáscar')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Malásia')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Maláui')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Maldivas')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Mali')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Malta')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Marrocos')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Maurícia')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Mauritânia')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('México')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Mianmar')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Micronésia')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Moçambique')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Moldávia')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Mónaco')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Mongólia')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Montenegro')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Namíbia')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Nauru')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Nepal')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Nicarágua')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Níger')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Nigéria')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Noruega')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Nova Zelândia')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Omã')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Países Baixos')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Palau')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Panamá')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Papua Nova Guiné')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Paquistão')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Paraguai')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Peru')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Polónia')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Portugal')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Quénia')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Quirguistão')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Quiribáti')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Reino Unido')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('República Centro-Africana')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('República Checa')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('República Democrática do Congo')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('República Dominicana')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Roménia')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Ruanda')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Rússia')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Salomão')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Salvador')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Samoa')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Santa Lúcia')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('São Cristóvão e Neves')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('São Marinho')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('São Tomé e Príncipe')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('São Vicente e Granadinas')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Seicheles')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Senegal')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Serra Leoa')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Sérvia')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Singapura')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Síria')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Somália')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Sri Lanca')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Suazilândia')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Sudão')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Sudão do Sul')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Suécia')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Suíça')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Suriname')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Tailândia')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Taiuã')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Tajiquistão')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Tanzânia')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Timor-Leste')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Togo')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Tonga')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Trindade e Tobago')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Tunísia')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Turcomenistão')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Turquia')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Tuvalu')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Ucrânia')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Uganda')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Uruguai')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Usbequistão')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Vanuatu')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Vaticano')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Venezuela')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Vietname')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Zâmbia')
INSERT INTO TB_ORIGEM (pais_origem) VALUES ('Zimbábue')