INSERT INTO TB_DIRETOR (nome_diretor) VALUES ('Stanley Kubrick')
INSERT INTO TB_DIRETOR (nome_diretor) VALUES ('Martin Scorsese')
INSERT INTO TB_DIRETOR (nome_diretor) VALUES ('Christopher Nolan')
INSERT INTO TB_DIRETOR (nome_diretor) VALUES ('Joel')
INSERT INTO TB_DIRETOR (nome_diretor) VALUES ('Ethan Coen')
INSERT INTO TB_DIRETOR (nome_diretor) VALUES ('Spike Jonze')
INSERT INTO TB_DIRETOR (nome_diretor) VALUES ('Steven Speilberg')
INSERT INTO TB_DIRETOR (nome_diretor) VALUES ('Gus Van Sant')
INSERT INTO TB_DIRETOR (nome_diretor) VALUES ('Quentin Tarantino')
INSERT INTO TB_DIRETOR (nome_diretor) VALUES ('Francis Ford Coppola')
INSERT INTO TB_DIRETOR (nome_diretor) VALUES ('Roman Polanski')
INSERT INTO TB_DIRETOR (nome_diretor) VALUES ('Wes Anderson')
INSERT INTO TB_DIRETOR (nome_diretor) VALUES ('Peter Jackson')
INSERT INTO TB_DIRETOR (nome_diretor) VALUES ('Tim Burton')
INSERT INTO TB_DIRETOR (nome_diretor) VALUES ('Alfred Hitchcock')
INSERT INTO TB_DIRETOR (nome_diretor) VALUES ('Spike Lee')
INSERT INTO TB_DIRETOR (nome_diretor) VALUES ('James Cameron')
INSERT INTO TB_DIRETOR (nome_diretor) VALUES ('Oliver Stone')
INSERT INTO TB_DIRETOR (nome_diretor) VALUES ('George Lucas')
INSERT INTO TB_DIRETOR (nome_diretor) VALUES ('Paul Thomas Anderson')
INSERT INTO TB_DIRETOR (nome_diretor) VALUES ('Ridley Scott')
INSERT INTO TB_DIRETOR (nome_diretor) VALUES ('Clint Eastwood')
INSERT INTO TB_DIRETOR (nome_diretor) VALUES ('Guy Ritchie')
INSERT INTO TB_DIRETOR (nome_diretor) VALUES ('Andy Wachowski')
INSERT INTO TB_DIRETOR (nome_diretor) VALUES ('Lana Wachowski')
INSERT INTO TB_DIRETOR (nome_diretor) VALUES ('Night Shyamalan')
INSERT INTO TB_DIRETOR (nome_diretor) VALUES ('Woody Allen')
INSERT INTO TB_DIRETOR (nome_diretor) VALUES ('Frank Darabont')
INSERT INTO TB_DIRETOR (nome_diretor) VALUES ('Akira Kurosawa')
INSERT INTO TB_DIRETOR (nome_diretor) VALUES ('Pedro Almodóvar')
INSERT INTO TB_DIRETOR (nome_diretor) VALUES ('Lars Von Trier')
INSERT INTO TB_DIRETOR (nome_diretor) VALUES ('Michael Haneke')
INSERT INTO TB_DIRETOR (nome_diretor) VALUES ('David Fincher')
INSERT INTO TB_DIRETOR (nome_diretor) VALUES ('Sofia Coppola')
INSERT INTO TB_DIRETOR (nome_diretor) VALUES ('Alejandro González Iñárritu')
INSERT INTO TB_DIRETOR (nome_diretor) VALUES ('Darren Aronofsky')
INSERT INTO TB_DIRETOR (nome_diretor) VALUES ('Federico Fellini')
INSERT INTO TB_DIRETOR (nome_diretor) VALUES ('Brian De Palma')
INSERT INTO TB_DIRETOR (nome_diretor) VALUES ('David Lynch')
INSERT INTO TB_DIRETOR (nome_diretor) VALUES ('Bernardo Bertolucci')